# SPDX-License-Identifier: Apache-2.0
# Reviewed minimal build of immutable C/C++ sources; no upstream generators.
get_filename_component(URE_TEXT_COMPONENT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(URE_HB_SOURCE "${URE_TEXT_COMPONENT}/src/upstream/text-layout/harfbuzz-14.5.1")
set(URE_FB_SOURCE "${URE_TEXT_COMPONENT}/src/upstream/text-layout/fribidi-1.0.17")
foreach(source IN ITEMS URE_HB_SOURCE URE_FB_SOURCE)
    if(NOT EXISTS "${${source}}/.uke-linux-owned")
        message(FATAL_ERROR "Run scripts/prepare-text-layout-sources.sh before configuring")
    endif()
endforeach()
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/harfbuzz-sources.list" hb_sources)
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/fribidi-sources.list" fb_sources)
list(TRANSFORM hb_sources PREPEND "${URE_HB_SOURCE}/")
list(TRANSFORM fb_sources PREPEND "${URE_FB_SOURCE}/")
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/harfbuzz-flags.list" hb_flags)
add_library(ure-harfbuzz STATIC ${hb_sources})
target_include_directories(ure-harfbuzz SYSTEM PUBLIC "${URE_HB_SOURCE}/src")
target_compile_features(ure-harfbuzz PUBLIC cxx_std_17)
target_compile_options(ure-harfbuzz PRIVATE ${hb_flags})
target_link_libraries(ure-harfbuzz PUBLIC freetype Threads::Threads)
add_library(ure-fribidi STATIC ${fb_sources})
target_include_directories(ure-fribidi SYSTEM PUBLIC "${URE_FB_SOURCE}" "${URE_FB_SOURCE}/lib")
target_compile_definitions(ure-fribidi PRIVATE HAVE_CONFIG_H)
set_target_properties(ure-fribidi PROPERTIES C_STANDARD 11)
if(CMAKE_CXX_FLAGS MATCHES "fsanitize")
    target_compile_options(ure-fribidi PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
endif()
